---
spring:
  config:
    activate:
      on-profile:
      - dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inv_mgmt
    username: root
    password: root
    
  jpa:
    show-sql: true
    generate-ddl: false
    
stocks:
  transport-type: Airways
  sla-days: 1  
...
---
spring:
  config:
    activate:
      on-profile:
      - dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inv_mgmt
    username: root
    password: root
    
  jpa:
    show-sql: true
    generate-ddl: false
    
stocks:
  transport-type: Seaways
  sla-days: 10  
...